CREATE TABLE DEMO_ORDER
(
  CODE            VARCHAR(20),
  STATE           VARCHAR(20),
  UPDATE_DATETIME DATETIME,
  ORDER_TYPE      VARCHAR(20)
);
-- --
CREATE TABLE DEMO_PACKAGE
(
  CODE            VARCHAR(20),
  STATE           VARCHAR(20),
  UPDATE_DATETIME DATETIME,
  ORDER_CODE      VARCHAR(20)
);
