INSERT INTO TEST_TABLE (TEST_CODE, TEST_VALUE, TEST_DATETIME, TEST_STATE) VALUES ('CODE_1', 'VALUE_1', GETDATE(), 'CREATED');
INSERT INTO TEST_TABLE (TEST_CODE, TEST_VALUE, TEST_DATETIME, TEST_STATE) VALUES ('CODE_2', 'VALUE_2', GETDATE(), 'IN_PROGRESS');
INSERT INTO TEST_TABLE (TEST_CODE, TEST_VALUE, TEST_DATETIME, TEST_STATE) VALUES ('CODE_3', 'VALUE_3', GETDATE(), 'FINISHED');